name: "default-network"
description: "The network description"
version: 1.0.0
client:
  organization: org1.example.com
  logging:
    level: info
  cryptoconfig:
    path: ${GOPATH}/src/shopBack/certs
    #path: /opt/app/fabric/cli/user/org1.example.com/Admin-peer0.org1.example.com
  credentialStore:
    path: /tmp/
    cryptoStore:
      path: /tmp/msp
  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256
  tlsCerts:
    systemCertPool: true
    client:
      key:
        path: ${GOPATH}/src/shopBack/certs/peerOrganizations/org1.example.com/users/Admin@org1.example.com/tls/client.key
        #path: /opt/app/fabric/cli/user/org1.example.com/Admin-peer0.org1.example.com/tls/client.key
      cert:
        path: ${GOPATH}/src/shopBack/certs/peerOrganizations/org1.example.com/users/Admin@org1.example.com/tls/client.crt
        #path: /opt/app/fabric/cli/user/org1.example.com/Admin-peer0.org1.example.com/tls/client.crt
channels:
  mychannel:
    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0
organizations:
  org1.example.com:
    mspid: Org1MSP
    cryptoPath: peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/
    #cryptoPath: msp/
    peers:
    - peer0.org1.example.com
orderers:
  orderer.org1.example.com:
    url: orderer.org1.example.com:7050
    grpcOptions:
      ssl-target-name-override: orderer.org1.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/shopBack/certs/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem
      #path: /opt/app/fabric/cli/user/org1.example.com/Admin-peer0.org1.example.com/tlsca.org1.example.com-cert.pem
peers:
  peer0.org1.example.com:
    url: peer0.org1.example.com:7051
    eventUrl: peer0.org1.example.com:7053
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/shopBack/certs/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      #path: /opt/app/fabric/cli/user/org1.example.com/Admin-peer0.org1.example.com/tls/ca.crt

entityMatchers:
  orderer:
  - pattern: (\w*)orderer.org1.example.com(\w*)
    urlSubstitutionExp: orderer.org1.example.com:7050
    sslTargetOverrideUrlSubstitutionExp: orderer.org1.example.com
    mappedHost: orderer.org1.example.com
